{% set name = "pynlp-lib" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pynlp-lib-{{ version }}.tar.gz
  sha256: 0747427f892bf27dfa6d62fe8c338b65b9adb57e1b61f43ac8c081c16f9fd4e3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - requests
    - deepgram-sdk

test:
  imports:
    - pynlpl
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pynlp-lib/
  summary: PyNLP Lib is an open source Python NLP library that provides functionality for both web and local development
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MattChanTK
